export enum CaseStatus {
  OPEN = "OPEN",
  UNDER_REVIEW = "UNDER_REVIEW",
  WAITING_EVIDENCE = "WAITING_EVIDENCE",
  RESOLVED = "RESOLVED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
  ESCALATED = "ESCALATED",
  CLOSED = "CLOSED",
}

export enum CaseType {
  COMPLAINT = "COMPLAINT",
  FRAUD_REPORT = "FRAUD_REPORT",
}

export enum Severity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum Verdict {
  VALID = "VALID",
  INVALID = "INVALID",
  INCONCLUSIVE = "INCONCLUSIVE",
}

export enum CaseCategory {
  // Complaints
  ORDER_QUALITY = "ORDER_QUALITY",
  MISSING_ITEM = "MISSING_ITEM",
  WRONG_ITEM = "WRONG_ITEM",
  FOOD_SAFETY = "FOOD_SAFETY",
  DELIVERY_LATE = "DELIVERY_LATE",
  NOT_RECEIVED = "NOT_RECEIVED",
  DRIVER_BEHAVIOR = "DRIVER_BEHAVIOR",
  MERCHANT_BEHAVIOR = "MERCHANT_BEHAVIOR",
  DAMAGED_ITEM = "DAMAGED_ITEM",
  UNAUTHORIZED_CANCEL = "UNAUTHORIZED_CANCEL",
  // Fraud
  FAKE_DELIVERY = "FAKE_DELIVERY",
  COD_THEFT = "COD_THEFT",
  ORDER_FARMING = "ORDER_FARMING",
  FAKE_REVIEW = "FAKE_REVIEW",
  PROMO_ABUSE = "PROMO_ABUSE",
  REFUND_ABUSE = "REFUND_ABUSE",
  MULTI_ACCOUNT = "MULTI_ACCOUNT",
  CHARGEBACK_FRAUD = "CHARGEBACK_FRAUD",
  GPS_SPOOFING = "GPS_SPOOFING",
  COLLUSION = "COLLUSION",
}

export type ActorType = "CONSUMER" | "DRIVER" | "MERCHANT" | "ADMIN" | "SYSTEM";

/** Categories that are treated as fraud (drive auto-detection rules). */
export const FRAUD_CATEGORIES: CaseCategory[] = [
  CaseCategory.FAKE_DELIVERY,
  CaseCategory.COD_THEFT,
  CaseCategory.ORDER_FARMING,
  CaseCategory.FAKE_REVIEW,
  CaseCategory.PROMO_ABUSE,
  CaseCategory.REFUND_ABUSE,
  CaseCategory.MULTI_ACCOUNT,
  CaseCategory.CHARGEBACK_FRAUD,
  CaseCategory.GPS_SPOOFING,
  CaseCategory.COLLUSION,
];
