export { httpClient, ApiError } from './http-client';
export { socketClient } from './socket-client';
export {
  authApi,
  consumerApi,
  merchantApi,
  orderApi,
  paymentApi,
  inventoryApi,
  driverApi,
  dispatchApi,
  shippingApi,
  walletApi,
  PORTS,
} from './api-endpoints';
export type {
  ShippingFeeRequest,
  ShippingFeeResponse,
} from './api-endpoints';
export type {
  ApiResponse,
  PaginatedResponse,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  UserRole,
  UserStatus,
  UserProfile,
  UserDetail,
  Gender,
  ConsumerProfile,
  Address,
  PaymentMethod,
  CreateConsumerRequest,
  AddAddressRequest,
  AddPaymentMethodRequest,
  MerchantStatus,
  CapacityStatus,
  Merchant,
  CreateMerchantRequest,
  MenuCategory,
  MenuItem,
  CreateMenuItemRequest,
  UpdateMenuItemRequest,
  OperatingHour,
  SetOperatingHoursRequest,
  UpdateCapacityRequest,
  OrderType,
  OrderStatus,
  OrderItem,
  Order,
  PlaceOrderRequest,
  CancelOrderRequest,
  RejectOrderRequest,
  OutForDeliveryRequest,
  UpdateOrderRequest,
  PaymentStatus,
  PaymentMethodType,
  Payment,
  CreatePaymentRequest,
  CompletePaymentRequest,
  FailPaymentRequest,
  RefundPaymentRequest,
  Inventory,
  InventoryReservation,
  CreateInventoryRequest,
  ReserveStockRequest,
  ReleaseStockRequest,
  ConsumeStockRequest,
  UpdateStockRequest,
  DriverStatus,
  VehicleType,
  Driver,
  RegisterDriverRequest,
  UpdateLocationRequest,
  DispatchStatus,
  Dispatch,
  CreateDispatchRequest,
  OrderStatusUpdate,
  DriverLocationUpdate,
} from './types';